version: '3.8'

services:
  backend:
    build: 
      context: ./DocumentWebsite.Server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./DocumentWebsite.Server/TextFiles:/app/TextFiles

  frontend:
    build:
      context: ./documentwebsite.client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
